In [6]:
import numpy as np

 

n= np.random.randint(2,5) 

A= np.random.randint(-5,5,size=(n,n)) 

print(f'A= \n{A}') 

 

def ryDet(A): 

     

    n= A.shape[0] 

    if n>1: 

        i= 0 

        Bi=  np.delete(A, i, axis=0) 

        #print(f'\ni= {i}, Bi= \n{Bi}') 

         

        det= 0 

        for j in range(n): 

             

            Bij= np.delete(Bi,j, axis=1) 

            print(f'\ni,j= {i}{j}, Bij= \n{Bij}') 

             

            Dij= ryDet(Bij) #np.linalg.det(Bij) 

            print(f'.... Dij= {Dij}') 

             

            Cij= A[i,j]*Dij*(-1)**(i+j) 

            det += Cij 

        #print(f'det= {det}') 

        return det 

     

    elif A.shape[0]==1: 

        det= A[0,0] 

        return det 

    else: 

        return None 

 

det= ryDet(A) 

print(f'\ndet= {det}')

A= 
[[ 0 -1 -3  2]
 [ 0 -2 -4 -2]
 [ 0  2 -5 -5]
 [-5  2  4  4]]

i,j= 00, Bij= 
[[-2 -4 -2]
 [ 2 -5 -5]
 [ 2  4  4]]

i,j= 00, Bij= 
[[-5 -5]
 [ 4  4]]

i,j= 00, Bij= 
[[4]]
.... Dij= 4

i,j= 01, Bij= 
[[4]]
.... Dij= 4
.... Dij= 0

i,j= 01, Bij= 
[[ 2 -5]
 [ 2  4]]

i,j= 00, Bij= 
[[4]]
.... Dij= 4

i,j= 01, Bij= 
[[2]]
.... Dij= 2
.... Dij= 18

i,j= 02, Bij= 
[[ 2 -5]
 [ 2  4]]

i,j= 00, Bij= 
[[4]]
.... Dij= 4

i,j= 01, Bij= 
[[2]]
.... Dij= 2
.... Dij= 18
.... Dij= 36

i,j= 01, Bij= 
[[ 0 -4 -2]
 [ 0 -5 -5]
 [-5  4  4]]

i,j= 00, Bij= 
[[-5 -5]
 [ 4  4]]

i,j= 00, Bij= 
[[4]]
.... Dij= 4

i,j= 01, Bij= 
[[4]]
.... Dij= 4
.... Dij= 0

i,j= 01, Bij= 
[[ 0 -5]
 [-5  4]]

i,j= 00, Bij= 
[[4]]
.... Dij= 4

i,j= 01, Bij= 
[[-5]]
.... Dij= -5
.... Dij= -25

i,j= 02, Bij= 
[[ 0 -5]
 [-5  4]]

i,j= 00, Bij= 
[[4]]
.... Dij= 4

i,j= 01, Bij= 
[[-5]]
.... Dij= -5
.... Dij= -25
.... Dij= -50

i,j= 02, Bij= 
[[ 0 -2 -2]
 [ 0  2 -5]
 [-5  2  4]]

i,j= 00, Bij= 
[[ 2 -5]
 [ 2  4]]

i,j= 00, Bij=