### EX.1

In [25]:
import numpy as np

a= np.random.randint(-6,6,size=(3,3)) 

b= np.random.randint(-6,6,size=(3,1)) 


x= np.linalg.solve(a, b) 

 
print( 

f''' 

n= {3},  

a= {a} 

b= {b} 

x= {x} 

''')

np.allclose(np.dot(a, x), b)

 

n= 3,  

a= [[-3 -4  2]
 [ 1  0 -1]
 [ 0 -5  2]] 

b= [[-6]
 [-3]
 [ 5]] 

x= [[4.30769231]
 [1.92307692]
 [7.30769231]] 




True

### EX.2

In [26]:
a= np.random.randint(-10,10,size=(5,5)) 

b= np.random.randint(1,10,size=(5,1)) 


x= np.linalg.solve(a, b) 

 
print( 

f''' 

n= {5},  

a= {a} 

b= {b} 

x= {x} 

''')

np.allclose(np.dot(a, x), b)

 

n= 5,  

a= [[-1 -1  6  2  2]
 [ 5  8  3  3 -5]
 [ 6  8  1 -7 -3]
 [ 1  0  2  3 -2]
 [ 7  1 -4 -2  1]] 

b= [[5]
 [6]
 [2]
 [9]
 [6]] 

x= [[ 2.31360332]
 [-2.44607625]
 [ 1.47752559]
 [-0.05325619]
 [-1.94555704]] 




True

### EX.3

In [27]:
a= np.random.randint(-10,10,size=(10,10)) 

b= np.random.randint(1,100,size=(10,1)) 


x= np.linalg.solve(a, b) 

 
print( 

f''' 

n= {10},  

a= {a} 

b= {b} 

x= {x} 

''')

np.allclose(np.dot(a, x), b)

 

n= 10,  

a= [[ -7   9   6  -3   8  -5   0  -5   7  -8]
 [  2 -10   1  -4   4  -1  -6  -6  -5  -3]
 [ -6   9   5   6   8  -8   2   7  -7  -7]
 [ -2   1  -9  -2  -4   1   1   1   6  -7]
 [  3  -6  -2   0  -8  -6  -8   2   3   8]
 [ -2  -8  -5  -3  -1  -1  -4   1   3   3]
 [ -5   5  -5   3   1  -2   2  -7  -1   4]
 [  6   3   6   4   4   1   9  -9   1 -10]
 [  4  -3  -7   2   8   2  -9  -9   7  -3]
 [ -4  -2  -7  -8  -3  -5  -8   3   6   1]] 

b= [[86]
 [ 5]
 [94]
 [69]
 [ 3]
 [95]
 [12]
 [17]
 [90]
 [46]] 

x= [[ -7.68634009]
 [-10.88677953]
 [ -3.24877332]
 [  8.70241036]
 [  7.48682378]
 [ -7.54669602]
 [  4.94672797]
 [  3.35916821]
 [  9.66549748]
 [ -3.41072432]] 




True